# Generated by Django 5.2 on 2025-07-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('variante', models.CharField(choices=[('carnivoro', 'Carnívoro'), ('vegetariano', 'Vegetariano'), ('saludable', 'Saludable')], max_length=20)),
                ('toppings', models.JSONField(default=list)),
                ('tamanio_cono', models.CharField(choices=[('pequeño', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], max_length=10)),
                ('fecha_pedido', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
